### ISSUE TITLE
non blocking interface

### ISSUE THREAD

**Issue by MasseGuillaume** [softwaremill/akka-http-session#17]
`setSession` implies a blocking interface. It would be nice if it could accept a `Future[T]`

**Comment by adamw** [comment]
In what sense is `setSession` blocking? If you have a future value, you can use `onSuccess` (a standard akka-http directive) to unwrap the value:

```
onSuccess(myFuture) { sessionContent =>
   setSession(sesisonContent) {
      // ...
   }
}
```

You could also easily make your own future-accepting directive. Does that work for you?

**Comment by MasseGuillaume** [comment]
Oh perfect I didn't know this one existed
