### ISSUE TITLE
add redirect helper to ctx

### ISSUE THREAD

**Issue by MasseGuillaume** [softwaremill/akka-http-session#18]
http://doc.akka.io/docs/akka/2.4.8/scala/http/routing-dsl/directives/route-directives/redirect.html

`ctx.redirect(url)`

**Comment by adamw** [comment]
But add it where specifically? :)

**Comment by MasseGuillaume** [comment]
oh wops ctx is of type `akka.http.scaladsl.server.RequestContext` this is an akka-http issue

**Comment by MasseGuillaume** [comment]
https://github.com/akka/akka/issues/21029
