### ISSUE TITLE
Version 0.1.2 not on maven central yet

### ISSUE THREAD

**Issue by afiore** [softwaremill/akka-http-session#2]
Hi, well done for upgrading to akka-http 1.0 so quickly! However, I [cannot find](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.softwaremill%22%20AND%20a%3A%22akka-http-session_2.11%22) `0.1.2` on Maven central yet. Am I missing something?

**Comment by adamw** [comment]
Should be there in max 15 minutes. Sorry! I didn't click the release button on sonatype :)

**Comment by afiore** [comment]
Hey, unfortunately the new release doesn't seem to be there yet!

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.softwaremill%22%20AND%20a%3A%22akka-http-session_2.11%22

**Comment by adamw** [comment]
I can see `0.1.2` :)

**Comment by adamw** [comment]
http://search.maven.org/#artifactdetails%7Ccom.softwaremill%7Cakka-http-session_2.11%7C0.1.2%7Cjar
