### ISSUE TITLE
Build for Scala 2.12.0

### ISSUE THREAD

**Issue by sometao** [softwaremill/akka-http-session#21]
any plan for artifacts for Scala 2.12?

**Comment by adamw** [comment]
Definitely, as soon as akka-http is available for 2.12 :) (https://github.com/akka/akka-http/issues/437)

**Comment by adamw** [comment]
I published 0.3.0-SNAPSHOT with the updated dependencies (akka-http 10.0.0-RC2) & cross-built for Scala 2.12

**Comment by adamw** [comment]
0.3.0 released
