### ISSUE TITLE
Duplicate Cookie/Header in response when sending an expired session and refresh token

### ISSUE THREAD

**Issue by kijanowski** [softwaremill/akka-http-session#28]
The cookie/header is set twice, the first time through `SessionDirectives.touchRequiredSession` and then again through `SessionDirectives.setOneOffSessionSameTransport`.
Tried to address it via https://github.com/softwaremill/akka-http-session/pull/27
but it's not fixed.

**Comment by mkubala** [comment]
Fixed in #62
