### ISSUE TITLE
JWTs

### ISSUE THREAD

**Issue by 0xdevalias** [softwaremill/akka-http-session#3]
Came across https://groups.google.com/forum/#!topic/akka-user/mZR0C5TRC04 and was wondering if any further thought had been put in to support JWTs? It'd be super useful!

**Comment by adamw** [comment]
Not yet - didn't have time so far :) But definitely on the radar. Help always appreciated :)

**Comment by 0xdevalias** [comment]
Fair fair :) In swapping from cookie based to something a little more 'modern' to make proper use of the JWT's would require having some frontend logic to handle them.

In regards to auth stuff I've seen [Satellizer](https://github.com/sahat/satellizer) used pretty well for that. Perhaps some lessons could be learned there?

**Comment by adamw** [comment]
I just release 0.2.0 with some basic support for JWT: sessions can be encoded in that format

**Comment by 0xdevalias** [comment]
Sounds good, will check it out :)
