### ISSUE TITLE
Grammar error in README

### ISSUE THREAD

**Issue by mingraham** [softwaremill/akka-http-session#31]
I have a local branch ready to be pushed (case of "using using" instead of "using"), but get a 403. How can I become a contributor?

**Comment by adamw** [comment]
I think you should first fork the repository to your account, then push the changes to a branch on your fork. Finally, when visiting the fork on GitHub, you should see a yellow box with an option to create a PR.

**Comment by mingraham** [comment]
Ah, thanks!
