### ISSUE TITLE
0.5.0 not published for scala 2.12

### ISSUE THREAD

**Issue by Krever** [softwaremill/akka-http-session#39]
Hi there,

it seems that version `0.5.0` was not published for scala `2.12`. Can you please do that ?:)

I base on [this](https://mvnrepository.com/artifact/com.softwaremill.akka-http-session/core_2.12) and [this](https://mvnrepository.com/artifact/com.softwaremill.akka-http-session/core_2.11)

Thanks.

**Comment by dimalusa** [comment]
I've got the same issue... Can you help us ?
Thanks.

**Comment by adamw** [comment]
It's there: http://repo1.maven.org/maven2/com/softwaremill/akka-http-session/core_2.12/0.5.0/

What's the dependency that you are trying to add and what's the error message?

**Comment by dimalusa** [comment]
Oh sorry, that was my mistake...
Everything is OK.
Thanks for you for this lib' !!

**Comment by adamw** [comment]
Good to hear, and glad you like it :)

**Comment by Krever** [comment]
Maybe it was still synchronizing when I created this issue. Now it is working perfectly fine, thanks!
