### ISSUE TITLE
Move oneOff, usingHeaders and maybe others

### ISSUE THREAD

**Issue by hseeberger** [softwaremill/akka-http-session#4]
I consider it confusing to have methods like `oneOff`, `usingHeaders` in `SessionDirectives`. They should be moved to some other trait or singleton object.

**Comment by adamw** [comment]
In fact there's an "import guide" missing currently which would be good to have :) How about having:
- `SessionDirectives` with `setSession`, `session`, etc.
- `SessionOptions` with `oneOff`, `usingCookies`, etc.

?

**Comment by hseeberger** [comment]
Sounds great!

**Comment by adamw** [comment]
Changed in 0.2.3, together with http-2.0
