### ISSUE TITLE
Question Regarding unresolved dependency: com.softwaremill#akka-http-session_2.12;0.5.2: not found

### ISSUE THREAD

**Issue by nmarasoiu** [softwaremill/akka-http-session#51]
Hi,
I am getting the mentioned error, "unresolved dependency: com.softwaremill#akka-http-session_2.12;0.5.2: not found".
In order to use your library as a dependency, we need likely this information:
- the repository 
- the scala versions for which it is compiled
- latest published version (in releases 0.5.2 is the latest, but in the commit log, 0.5.3)
Thank you
Nicu

**Comment by adamw** [comment]
0.5.3 is the latest version: https://repo1.maven.org/maven2/com/softwaremill/akka-http-session/core_2.12/0.5.3/

You don't need any repositories, it's in central. The group id is `com.softwaremill.akka-http-session`, the artifact id `core` and version `0.5.3`. Hope this helps!

**Comment by nmarasoiu** [comment]
Thank you!
