### ISSUE TITLE
on secret management

### ISSUE THREAD

**Issue by nmarasoiu** [softwaremill/akka-http-session#52]
Hi,
I would see two possibilities of managing the secret per env:
- via Kubernetes secrets, that is as a specific kind of configuration (secret one)
- automatically generating a secret when an environment starts - but where to keep it? Would the database be a proper place? I know for secret data there is Vault for instance, but that would make it too complex for us to choose.
What is your advice?
Thank you,
Nicu

**Comment by adamw** [comment]
I think that is very project-specific. You might use vault, you might use an AWS/Google service, keep it in database ... 

Closing as this isn't really in scope of akka-http-session
