### ISSUE TITLE
create pekko equivalent?

### ISSUE THREAD

**Issue by pjfanning** [softwaremill/akka-http-session#88]
I created https://github.com/pjfanning/pekko-http-session but it would possibly be tidier if there was a softwaremill/pekko-http-session.

**Comment by adamw** [comment]
Maybe we could simply have pekko-core modules here? Possibly using a different organization (`com.softwaremill.pekko-http-session`)

**Comment by pjfanning** [comment]
> Maybe we could simply have pekko-core modules here? Possibly using a different organization (`com.softwaremill.pekko-http-session`)

Is the idea to not have a 'jwt' lib for Pekko?

**Comment by adamw** [comment]
Ah no, we could similarly have `pekko-jwt` :) A direct copy of the akka variant, just in the same project

**Comment by pjfanning** [comment]
#89 merged
